/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AppPortalRouteImport } from './routes/_app/portal'
import { Route as AppTeamRouteImport } from './routes/_app/team'
import { Route as AcceptTokenRouteImport } from './routes/accept.$token'
import { Route as SignInIndexRouteImport } from './routes/sign-in/index'
import { Route as SignInVerifyRouteImport } from './routes/sign-in/verify'
import { Route as AppClientsIndexRouteImport } from './routes/_app/clients/index'
import { Route as AppClientsClientIdRouteImport } from './routes/_app/clients/$clientId'
import { Route as AppClientsNewRouteImport } from './routes/_app/clients/new'
import { Route as AppPlatformFirmsRouteImport } from './routes/_app/platform/firms'
import { Route as AppClientsClientIdIndexRouteImport } from './routes/_app/clients/$clientId/index'
import { Route as AppClientsClientIdProfileRouteImport } from './routes/_app/clients/$clientId/profile'
import { Route as AppClientsClientIdDocumentsIndexRouteImport } from './routes/_app/clients/$clientId/documents/index'
import { Route as AppClientsClientIdDocumentsDocIdRouteImport } from './routes/_app/clients/$clientId/documents/$docId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppPortalRoute = AppPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AcceptTokenRoute = AcceptTokenRouteImport.update({
  id: '/accept/$token',
  path: '/accept/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInIndexRoute = SignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInVerifyRoute = SignInVerifyRouteImport.update({
  id: '/sign-in/verify',
  path: '/sign-in/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AppClientsIndexRoute = AppClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsClientIdRoute = AppClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsNewRoute = AppClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => AppRoute,
} as any)
const AppPlatformFirmsRoute = AppPlatformFirmsRouteImport.update({
  id: '/platform/firms',
  path: '/platform/firms',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsClientIdIndexRoute = AppClientsClientIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppClientsClientIdRoute,
} as any)
const AppClientsClientIdProfileRoute =
  AppClientsClientIdProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AppClientsClientIdRoute,
  } as any)
const AppClientsClientIdDocumentsIndexRoute =
  AppClientsClientIdDocumentsIndexRouteImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => AppClientsClientIdRoute,
  } as any)
const AppClientsClientIdDocumentsDocIdRoute =
  AppClientsClientIdDocumentsDocIdRouteImport.update({
    id: '/documents/$docId',
    path: '/documents/$docId',
    getParentRoute: () => AppClientsClientIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inbox': typeof AppInboxRoute
  '/portal': typeof AppPortalRoute
  '/team': typeof AppTeamRoute
  '/accept/$token': typeof AcceptTokenRoute
  '/sign-in/verify': typeof SignInVerifyRoute
  '/sign-in/': typeof SignInIndexRoute
  '/clients/$clientId': typeof AppClientsClientIdRouteWithChildren
  '/clients/new': typeof AppClientsNewRoute
  '/platform/firms': typeof AppPlatformFirmsRoute
  '/clients/': typeof AppClientsIndexRoute
  '/clients/$clientId/profile': typeof AppClientsClientIdProfileRoute
  '/clients/$clientId/': typeof AppClientsClientIdIndexRoute
  '/clients/$clientId/documents/$docId': typeof AppClientsClientIdDocumentsDocIdRoute
  '/clients/$clientId/documents/': typeof AppClientsClientIdDocumentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inbox': typeof AppInboxRoute
  '/portal': typeof AppPortalRoute
  '/team': typeof AppTeamRoute
  '/accept/$token': typeof AcceptTokenRoute
  '/sign-in/verify': typeof SignInVerifyRoute
  '/sign-in': typeof SignInIndexRoute
  '/clients/new': typeof AppClientsNewRoute
  '/platform/firms': typeof AppPlatformFirmsRoute
  '/clients': typeof AppClientsIndexRoute
  '/clients/$clientId/profile': typeof AppClientsClientIdProfileRoute
  '/clients/$clientId': typeof AppClientsClientIdIndexRoute
  '/clients/$clientId/documents/$docId': typeof AppClientsClientIdDocumentsDocIdRoute
  '/clients/$clientId/documents': typeof AppClientsClientIdDocumentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/inbox': typeof AppInboxRoute
  '/_app/portal': typeof AppPortalRoute
  '/_app/team': typeof AppTeamRoute
  '/accept/$token': typeof AcceptTokenRoute
  '/sign-in/verify': typeof SignInVerifyRoute
  '/sign-in/': typeof SignInIndexRoute
  '/_app/clients/$clientId': typeof AppClientsClientIdRouteWithChildren
  '/_app/clients/new': typeof AppClientsNewRoute
  '/_app/platform/firms': typeof AppPlatformFirmsRoute
  '/_app/clients/': typeof AppClientsIndexRoute
  '/_app/clients/$clientId/profile': typeof AppClientsClientIdProfileRoute
  '/_app/clients/$clientId/': typeof AppClientsClientIdIndexRoute
  '/_app/clients/$clientId/documents/$docId': typeof AppClientsClientIdDocumentsDocIdRoute
  '/_app/clients/$clientId/documents/': typeof AppClientsClientIdDocumentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inbox'
    | '/portal'
    | '/team'
    | '/accept/$token'
    | '/sign-in/verify'
    | '/sign-in/'
    | '/clients/$clientId'
    | '/clients/new'
    | '/platform/firms'
    | '/clients/'
    | '/clients/$clientId/profile'
    | '/clients/$clientId/'
    | '/clients/$clientId/documents/$docId'
    | '/clients/$clientId/documents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inbox'
    | '/portal'
    | '/team'
    | '/accept/$token'
    | '/sign-in/verify'
    | '/sign-in'
    | '/clients/new'
    | '/platform/firms'
    | '/clients'
    | '/clients/$clientId/profile'
    | '/clients/$clientId'
    | '/clients/$clientId/documents/$docId'
    | '/clients/$clientId/documents'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/inbox'
    | '/_app/portal'
    | '/_app/team'
    | '/accept/$token'
    | '/sign-in/verify'
    | '/sign-in/'
    | '/_app/clients/$clientId'
    | '/_app/clients/new'
    | '/_app/platform/firms'
    | '/_app/clients/'
    | '/_app/clients/$clientId/profile'
    | '/_app/clients/$clientId/'
    | '/_app/clients/$clientId/documents/$docId'
    | '/_app/clients/$clientId/documents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AcceptTokenRoute: typeof AcceptTokenRoute
  SignInVerifyRoute: typeof SignInVerifyRoute
  SignInIndexRoute: typeof SignInIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portal': {
      id: '/_app/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AppPortalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/accept/$token': {
      id: '/accept/$token'
      path: '/accept/$token'
      fullPath: '/accept/$token'
      preLoaderRoute: typeof AcceptTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof SignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/verify': {
      id: '/sign-in/verify'
      path: '/sign-in/verify'
      fullPath: '/sign-in/verify'
      preLoaderRoute: typeof SignInVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/clients/': {
      id: '/_app/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AppClientsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/$clientId': {
      id: '/_app/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AppClientsClientIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/new': {
      id: '/_app/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof AppClientsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/platform/firms': {
      id: '/_app/platform/firms'
      path: '/platform/firms'
      fullPath: '/platform/firms'
      preLoaderRoute: typeof AppPlatformFirmsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/$clientId/': {
      id: '/_app/clients/$clientId/'
      path: '/'
      fullPath: '/clients/$clientId/'
      preLoaderRoute: typeof AppClientsClientIdIndexRouteImport
      parentRoute: typeof AppClientsClientIdRoute
    }
    '/_app/clients/$clientId/profile': {
      id: '/_app/clients/$clientId/profile'
      path: '/profile'
      fullPath: '/clients/$clientId/profile'
      preLoaderRoute: typeof AppClientsClientIdProfileRouteImport
      parentRoute: typeof AppClientsClientIdRoute
    }
    '/_app/clients/$clientId/documents/': {
      id: '/_app/clients/$clientId/documents/'
      path: '/documents'
      fullPath: '/clients/$clientId/documents/'
      preLoaderRoute: typeof AppClientsClientIdDocumentsIndexRouteImport
      parentRoute: typeof AppClientsClientIdRoute
    }
    '/_app/clients/$clientId/documents/$docId': {
      id: '/_app/clients/$clientId/documents/$docId'
      path: '/documents/$docId'
      fullPath: '/clients/$clientId/documents/$docId'
      preLoaderRoute: typeof AppClientsClientIdDocumentsDocIdRouteImport
      parentRoute: typeof AppClientsClientIdRoute
    }
  }
}

interface AppClientsClientIdRouteChildren {
  AppClientsClientIdProfileRoute: typeof AppClientsClientIdProfileRoute
  AppClientsClientIdIndexRoute: typeof AppClientsClientIdIndexRoute
  AppClientsClientIdDocumentsDocIdRoute: typeof AppClientsClientIdDocumentsDocIdRoute
  AppClientsClientIdDocumentsIndexRoute: typeof AppClientsClientIdDocumentsIndexRoute
}

const AppClientsClientIdRouteChildren: AppClientsClientIdRouteChildren = {
  AppClientsClientIdProfileRoute: AppClientsClientIdProfileRoute,
  AppClientsClientIdIndexRoute: AppClientsClientIdIndexRoute,
  AppClientsClientIdDocumentsDocIdRoute: AppClientsClientIdDocumentsDocIdRoute,
  AppClientsClientIdDocumentsIndexRoute: AppClientsClientIdDocumentsIndexRoute,
}

const AppClientsClientIdRouteWithChildren =
  AppClientsClientIdRoute._addFileChildren(AppClientsClientIdRouteChildren)

interface AppRouteChildren {
  AppInboxRoute: typeof AppInboxRoute
  AppPortalRoute: typeof AppPortalRoute
  AppTeamRoute: typeof AppTeamRoute
  AppClientsClientIdRoute: typeof AppClientsClientIdRouteWithChildren
  AppClientsNewRoute: typeof AppClientsNewRoute
  AppPlatformFirmsRoute: typeof AppPlatformFirmsRoute
  AppClientsIndexRoute: typeof AppClientsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppInboxRoute: AppInboxRoute,
  AppPortalRoute: AppPortalRoute,
  AppTeamRoute: AppTeamRoute,
  AppClientsClientIdRoute: AppClientsClientIdRouteWithChildren,
  AppClientsNewRoute: AppClientsNewRoute,
  AppPlatformFirmsRoute: AppPlatformFirmsRoute,
  AppClientsIndexRoute: AppClientsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AcceptTokenRoute: AcceptTokenRoute,
  SignInVerifyRoute: SignInVerifyRoute,
  SignInIndexRoute: SignInIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
