-- The platform store (agentledger.security.platform): firms, their wrapped data keys, users, invitations, MFA
-- challenges, sessions, engagement grants, the authentication log, offboarding and provisioning records.
--
-- One schema in the admin database, read and written by its own runtime login role {{app_role}}
-- (rt_<database>_platform), which owns nothing and has no privilege outside this schema; owner credentials only
-- migrate it (`agentledger platform migrate`). The columns mirror the SQLite platform schema the code was written
-- against: dates are text (ISO 8601 as the application writes them, or 'YYYY-MM-DD HH24:MI:SS' as SQLite's
-- datetime('now') writes them, which the compatibility layer reproduces here), flags and counters are integers.
-- No foreign keys: platform administrators belong to the firm '_platform', which has no row in firms.

CREATE TABLE firms (
    id               text PRIMARY KEY,
    name             text NOT NULL,
    status           text NOT NULL DEFAULT 'active',
    created_at       text NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    deleted_at       text,
    offboarding_from text,
    -- Where the firm's objects live ('file', 's3:<bucket>/<prefix>'), recorded once at creation; offboarding removes
    -- them from there, whatever the job's own settings say.
    blob_location    text
);

-- Each firm's data keys, wrapped with the master key (agentledger.security.crypto). Destroying them (wrapped set to
-- empty, destroyed_at set) is how a firm's data is crypto-shredded.
CREATE TABLE firm_keys (
    firm_id      text NOT NULL,
    version      int NOT NULL,
    wrapped      bytea NOT NULL,
    created_at   text NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    destroyed_at text,
    PRIMARY KEY (firm_id, version)
);

CREATE TABLE users (
    id                  text PRIMARY KEY,
    firm_id             text NOT NULL,
    email               text NOT NULL,
    name                text NOT NULL,
    role                text NOT NULL CHECK (role IN ('platform_admin', 'firm_admin', 'cpa', 'staff', 'client')),
    client_id           text,
    password_hash       text NOT NULL,
    totp_secret         text,
    totp_last_step      bigint,
    mfa_enrolled_at     text,
    failed_logins       int NOT NULL DEFAULT 0,
    locked_until        text,
    disabled            int NOT NULL DEFAULT 0,
    created_at          text NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    last_login_at       text,
    idp_subject         text,
    reviewer            int NOT NULL DEFAULT 0,
    reviewer_credential text
);
-- One account per email address whatever its case (SQLite: COLLATE NOCASE); the application stores it lower-cased.
CREATE UNIQUE INDEX users_email ON users (lower(email));
CREATE UNIQUE INDEX users_idp_subject ON users (idp_subject) WHERE idp_subject IS NOT NULL;

CREATE TABLE invites (
    token_hash  text PRIMARY KEY,
    firm_id     text NOT NULL,
    email       text NOT NULL,
    role        text NOT NULL,
    client_id   text,
    created_by  text NOT NULL,
    created_at  text NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    expires_at  text NOT NULL,
    accepted_at text
);

CREATE TABLE challenges (
    token_hash     text PRIMARY KEY,
    user_id        text NOT NULL,
    kind           text NOT NULL CHECK (kind IN ('mfa', 'enroll')),
    pending_secret text,
    expires_at     text NOT NULL,
    used_at        text
);

CREATE TABLE sessions (
    token_hash       text PRIMARY KEY,
    user_id          text NOT NULL,
    created_at       text NOT NULL,
    last_seen_at     text NOT NULL,
    expires_at       text NOT NULL,
    ip               text,
    user_agent       text,
    revoked_at       text,
    auth_method      text NOT NULL DEFAULT 'password+totp',
    stepped_up_at    text,
    authenticated_at text
);

-- Every authentication event, append-only.
CREATE TABLE auth_events (
    id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    at      text NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    firm_id text,
    user_id text,
    email   text,
    event   text NOT NULL,
    ip      text,
    detail  text
);

CREATE TABLE engagement_grants (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firm_id    text NOT NULL,
    user_id    text NOT NULL,
    client_id  text NOT NULL,
    granted_by text NOT NULL,
    granted_at text NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    revoked_by text,
    revoked_at text
);
CREATE INDEX engagement_grants_user ON engagement_grants (user_id, client_id);

-- What a deleted firm's store held, kept after the store is destroyed (holds, counts, audit head); append-only.
CREATE TABLE firm_offboarding (
    id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firm_id text NOT NULL,
    at      text NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    by      text NOT NULL,
    reason  text NOT NULL,
    summary text NOT NULL
);

-- One offboarding run at a time per firm (a lease), and a cancellation requested while one runs.
CREATE TABLE offboarding_runs (
    firm_id             text PRIMARY KEY,
    holder              text,
    lease_until         text,
    cancel_requested_at text,
    cancel_by           text,
    cancel_reason       text
);

-- How far a firm's destruction got (sealed, store_removing, store_removed, blobs_removed, tenant_removed,
-- key_shredded): a retry resumes, and a store recorded as removed is never mistaken for one that cannot be found.
CREATE TABLE firm_destruction (
    firm_id text NOT NULL,
    stage   text NOT NULL,
    detail  text NOT NULL DEFAULT '',
    at      text NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    PRIMARY KEY (firm_id, stage)
);

-- An SSO customer's own identity provider enforces MFA (reviewed evidence); without it SSO sign-ins are refused.
CREATE TABLE sso_mfa_attestations (
    organization_id text PRIMARY KEY,
    firm_id         text NOT NULL,
    evidence        text NOT NULL,
    attested_by     text NOT NULL,
    attested_at     text NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    revoked_at      text
);

-- Hosted sign-ins in flight (WorkOS AuthKit): the PKCE verifier sealed with the platform key, single use.
CREATE TABLE idp_states (
    state_hash   text PRIMARY KEY,
    purpose      text NOT NULL CHECK (purpose IN ('login', 'invite', 'link', 'step_up')),
    invite_hash  text,
    session_hash text,
    verifier     text NOT NULL,
    redirect_uri text NOT NULL,
    expires_at   text NOT NULL,
    used_at      text,
    browser_hash text
);

-- The provisioning journal (agentledger.pg.provision.Journal): what store each firm got, how far its creation got,
-- and the lease of the attempt in progress.
CREATE TABLE provisioning (
    firm_id     text PRIMARY KEY,
    resource    text,
    name        text,
    state       text CHECK (state IN ('creating', 'created', 'migrated', 'ready', 'removed')),
    holder      text,
    lease_until text,
    error       text,
    updated_at  text NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    database    text,
    server      text
);

-- ------------------------------------------------------------------------------------------------- immutability
-- The authentication log and the offboarding records are never rewritten, by anyone: the runtime role has no
-- UPDATE or DELETE on them, and these triggers refuse the owner too. AL006 maps to db.IntegrityError.
CREATE FUNCTION platform_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION '% is append-only: % refused', TG_TABLE_NAME, TG_OP USING ERRCODE = 'AL006';
END $$;

CREATE TRIGGER auth_events_append_only BEFORE UPDATE OR DELETE ON auth_events
    FOR EACH ROW EXECUTE FUNCTION platform_append_only();
CREATE TRIGGER auth_events_no_truncate BEFORE TRUNCATE ON auth_events
    FOR EACH STATEMENT EXECUTE FUNCTION platform_append_only();
CREATE TRIGGER firm_offboarding_append_only BEFORE UPDATE OR DELETE ON firm_offboarding
    FOR EACH ROW EXECUTE FUNCTION platform_append_only();
CREATE TRIGGER firm_offboarding_no_truncate BEFORE TRUNCATE ON firm_offboarding
    FOR EACH STATEMENT EXECUTE FUNCTION platform_append_only();

-- ------------------------------------------------------------------------------------------------- privileges
-- Exactly what agentledger.security.platform and agentledger.security.crypto execute, nothing more: no DELETE except
-- the destruction stages a cancelled offboarding takes back, no privilege on schema_migrations, no DDL.
DO $$
BEGIN
    EXECUTE format('GRANT USAGE ON SCHEMA %I TO {{app_role}}', current_schema());
    EXECUTE format('REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA %I FROM PUBLIC', current_schema());
END $$;
GRANT SELECT, INSERT, UPDATE ON firms, firm_keys, users, invites, challenges, sessions, engagement_grants, offboarding_runs,
    sso_mfa_attestations, idp_states, provisioning TO {{app_role}};
GRANT SELECT, INSERT ON auth_events, firm_offboarding TO {{app_role}};
GRANT SELECT, INSERT, DELETE ON firm_destruction TO {{app_role}};
