-- The rest of a firm's operational store, moved from SQLite (agentledger.db) onto PostgreSQL.
-- Column names and value formats match the SQLite schema, so every module runs unchanged on either backend:
-- JSON stays in text columns and dates written by the application stay ISO text. The financial tables keep the
-- stronger rules of 0001: the application role still cannot write entries, postings, receipts or audit records,
-- and closed_through moves only through close_period/reopen_period.

-- ------------------------------------------------------------------------------------------------- clients
ALTER TABLE clients
    ADD COLUMN entity_type     text,
    ADD COLUMN formed_under    text NOT NULL DEFAULT 'domestic',
    ADD COLUMN tax_id_last4    text,
    ADD COLUMN emails          text NOT NULL DEFAULT '[]',
    ADD COLUMN aliases         text NOT NULL DEFAULT '[]',
    ADD COLUMN consent_7216_at text,
    ADD COLUMN domain          text NOT NULL DEFAULT 'general',
    ADD COLUMN facts           text NOT NULL DEFAULT '{}';

-- ------------------------------------------------------------------------------------------------- operational tables
CREATE TABLE assets (
    client_id         text NOT NULL REFERENCES clients(id),
    id                text NOT NULL,
    description       text NOT NULL,
    cost              text NOT NULL,
    acquired          text NOT NULL,
    placed_in_service text NOT NULL,
    recovery_years    int NOT NULL,
    book_life_years   int NOT NULL,
    sec179_elected    text NOT NULL DEFAULT '0',
    PRIMARY KEY (client_id, id)
);

CREATE TABLE documents (
    id            text PRIMARY KEY,
    client_id     text REFERENCES clients(id),
    sha256        text NOT NULL UNIQUE,
    original_name text NOT NULL,
    media_type    text NOT NULL,
    channel       text NOT NULL,
    received_at   text NOT NULL,
    sender        text,
    parent_id     text,
    doc_type      text,
    tax_year      int,
    confidence    double precision,
    status        text NOT NULL,
    vault_path    text,
    fields        text NOT NULL DEFAULT '{}',
    summary       text,
    classified_by text,
    text_excerpt  text
);

CREATE TABLE entry_documents (
    entry_id    bigint NOT NULL REFERENCES entries(id),
    document_id text NOT NULL REFERENCES documents(id),
    linked_by   text NOT NULL,
    at          text NOT NULL,
    PRIMARY KEY (entry_id, document_id)
);

-- Receipts for application commands (invoices, payments), keyed by scope; ledger receipts stay in `commands`.
CREATE TABLE app_commands (
    scope        text NOT NULL,
    command_id   text NOT NULL,
    kind         text NOT NULL,
    payload_hash text NOT NULL,
    result       text NOT NULL,
    created_at   timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (scope, command_id)
);

CREATE TABLE info_returns (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id   text NOT NULL REFERENCES clients(id),
    document_id text REFERENCES documents(id),
    form        text NOT NULL,
    tax_year    int NOT NULL,
    payer       text,
    amount      text NOT NULL
);

CREATE TABLE findings (
    id         text PRIMARY KEY,
    client_id  text NOT NULL REFERENCES clients(id),
    check_id   text NOT NULL,
    severity   text NOT NULL CHECK (severity IN ('info', 'low', 'medium', 'high', 'critical')),
    title      text NOT NULL,
    detail     text NOT NULL,
    evidence   text NOT NULL DEFAULT '[]',
    citation   text,
    owner      text NOT NULL CHECK (owner IN ('client', 'cpa', 'both')),
    tax_year   int,
    first_seen text NOT NULL
);

CREATE TABLE finding_resolutions (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    finding_id text NOT NULL REFERENCES findings(id),
    actor      text NOT NULL,
    role       text NOT NULL,
    action     text NOT NULL CHECK (action IN ('explained', 'corrected', 'accepted_risk', 'reopened')),
    note       text NOT NULL,
    at         text NOT NULL
);

CREATE TABLE precedents (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic      text NOT NULL,
    situation  text NOT NULL,
    judgment   text NOT NULL,
    citations  text NOT NULL DEFAULT '[]',
    domain     text,
    author     text NOT NULL,
    client_id  text,
    at         text NOT NULL
);

CREATE TABLE contacts (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id  text NOT NULL REFERENCES clients(id),
    name       text NOT NULL,
    email      text,
    phone      text,
    role       text,
    is_primary int NOT NULL DEFAULT 0
);

CREATE TABLE engagements (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id  text NOT NULL REFERENCES clients(id),
    type       text NOT NULL,
    tax_year   int,
    stage      text NOT NULL,
    owner      text,
    due_date   text,
    fee        text,
    created_at text NOT NULL
);

CREATE TABLE tasks (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id     text REFERENCES clients(id),
    engagement_id bigint REFERENCES engagements(id),
    title         text NOT NULL,
    detail        text NOT NULL DEFAULT '',
    assignee      text NOT NULL CHECK (assignee IN ('cpa', 'client', 'agent')),
    due           text,
    status        text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'done', 'cancelled')),
    source        text NOT NULL,
    dedupe_key    text UNIQUE,
    created_at    text NOT NULL,
    done_at       text,
    done_note     text
);

CREATE TABLE messages (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id  text REFERENCES clients(id),
    direction  text NOT NULL CHECK (direction IN ('in', 'out')),
    channel    text NOT NULL,
    to_addr    text,
    subject    text NOT NULL,
    body       text NOT NULL,
    status     text NOT NULL CHECK (status IN ('draft', 'sent', 'received', 'failed')),
    source     text NOT NULL,
    dedupe_key text UNIQUE,
    at         text NOT NULL
);

CREATE TABLE parties (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id   text NOT NULL REFERENCES clients(id),
    kind        text NOT NULL CHECK (kind IN ('customer', 'vendor', 'both')),
    name        text NOT NULL,
    email       text,
    phone       text,
    tin_last4   text,
    entity_type text,
    w9_on_file  int NOT NULL DEFAULT 0,
    terms_days  int NOT NULL DEFAULT 30,
    notes       text NOT NULL DEFAULT '',
    created_at  text NOT NULL
);

CREATE TABLE deals (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id      text NOT NULL REFERENCES clients(id),
    party_id       bigint REFERENCES parties(id),
    title          text NOT NULL,
    stage          text NOT NULL,
    value          text NOT NULL DEFAULT '0',
    expected_close text,
    created_at     text NOT NULL
);

CREATE TABLE invoices (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id     text NOT NULL REFERENCES clients(id),
    party_id      bigint NOT NULL REFERENCES parties(id),
    number        text NOT NULL,
    issued        text NOT NULL,
    due           text NOT NULL,
    amount        text NOT NULL,
    sales_tax     text NOT NULL DEFAULT '0',
    description   text NOT NULL,
    entry_id      bigint REFERENCES entries(id),
    status        text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'paid', 'void')),
    paid_entry_id bigint REFERENCES entries(id),
    UNIQUE (client_id, number)
);

CREATE TABLE kv (
    key   text PRIMARY KEY,
    value text NOT NULL
);

CREATE TABLE ai_usage (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    at            text NOT NULL,
    tier          text NOT NULL,
    model         text NOT NULL,
    task          text NOT NULL,
    client_id     text,
    input_tokens  int,
    output_tokens int,
    ok            int NOT NULL,
    note          text
);

CREATE TABLE tax_returns (
    id         text PRIMARY KEY,
    client_id  text NOT NULL REFERENCES clients(id),
    tax_year   int NOT NULL,
    form       text NOT NULL,
    created_at text NOT NULL,
    created_by text NOT NULL,
    amends     text REFERENCES tax_returns(id),
    UNIQUE (client_id, tax_year, form)
);

CREATE TABLE tax_return_versions (
    return_id   text NOT NULL REFERENCES tax_returns(id),
    version     int NOT NULL,
    inputs      text NOT NULL,
    provenance  text NOT NULL,
    result      text,
    summary     text NOT NULL DEFAULT '{}',
    diagnostics text NOT NULL DEFAULT '[]',
    crosscheck  text,
    input_hash  text NOT NULL,
    created_at  text NOT NULL,
    created_by  text NOT NULL,
    note        text NOT NULL DEFAULT '',
    PRIMARY KEY (return_id, version)
);

CREATE TABLE workflow_events (
    workflow_id     text NOT NULL,
    seq             int NOT NULL,
    kind            text NOT NULL,
    event           text NOT NULL,
    data            text NOT NULL,
    actor           text NOT NULL,
    at              text NOT NULL,
    idempotency_key text,
    prev_hash       text NOT NULL,
    hash            text NOT NULL,
    PRIMARY KEY (workflow_id, seq)
);
CREATE UNIQUE INDEX workflow_idem ON workflow_events (workflow_id, idempotency_key) WHERE idempotency_key IS NOT NULL;

CREATE INDEX documents_client ON documents (client_id);
CREATE INDEX tasks_client ON tasks (client_id, status);
CREATE INDEX audit_client ON audit (client_id, seq);

-- ------------------------------------------------------------------------------------------------- append-only
DO $$
DECLARE
    t text;
BEGIN
    FOREACH t IN ARRAY ARRAY['app_commands', 'entry_documents', 'info_returns', 'finding_resolutions', 'precedents',
                             'ai_usage', 'tax_return_versions', 'workflow_events'] LOOP
        EXECUTE format('CREATE TRIGGER %I BEFORE UPDATE OR DELETE ON %I FOR EACH ROW EXECUTE FUNCTION forbid_change()',
                       t || '_immutable', t);
        EXECUTE format('CREATE TRIGGER %I BEFORE TRUNCATE ON %I FOR EACH STATEMENT EXECUTE FUNCTION forbid_change()',
                       t || '_no_truncate', t);
    END LOOP;
END $$;

-- ------------------------------------------------------------------------------------------------- row-level security
-- Client-owned rows are visible and writable only for clients in the session's scope. Rows without a client
-- (firm-wide precedents, usage, tasks) are firm data.
DO $$
DECLARE
    t text;
BEGIN
    FOREACH t IN ARRAY ARRAY['assets', 'documents', 'info_returns', 'findings', 'precedents', 'contacts', 'engagements',
                             'tasks', 'messages', 'parties', 'deals', 'invoices', 'ai_usage', 'tax_returns'] LOOP
        EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
        EXECUTE format('CREATE POLICY %I ON %I USING (client_id IS NULL OR in_scope(client_id)) '
                       'WITH CHECK (client_id IS NULL OR in_scope(client_id))', 'scope_' || t, t);
    END LOOP;
END $$;
CREATE POLICY write_clients  ON clients  FOR INSERT WITH CHECK (in_scope(id));
CREATE POLICY update_clients ON clients  FOR UPDATE USING (in_scope(id)) WITH CHECK (in_scope(id));
CREATE POLICY write_accounts ON accounts FOR INSERT WITH CHECK (in_scope(client_id));

-- ------------------------------------------------------------------------------------------------- privileges
GRANT SELECT, INSERT ON app_commands, entry_documents, info_returns, finding_resolutions, precedents, ai_usage,
    tax_return_versions, workflow_events TO agentledger_app;
GRANT SELECT, INSERT, UPDATE ON assets, documents, findings, contacts, engagements, tasks, messages, parties, deals,
    invoices, kv, tax_returns TO agentledger_app;
-- Clients: everything except the books' close date and currency, which move only through the ledger functions.
GRANT INSERT (id, name, kind, entity_type, formed_under, tax_id_last4, emails, aliases, consent_7216_at, domain, facts)
    ON clients TO agentledger_app;
GRANT UPDATE (name, entity_type, formed_under, tax_id_last4, emails, aliases, consent_7216_at, domain, facts)
    ON clients TO agentledger_app;
GRANT INSERT ON accounts TO agentledger_app;
