-- Evidence lifecycle (backlog F-06): content-addressed versions, retention, legal holds and deletion receipts.
-- Same columns and formats as the SQLite schema in agentledger.db.

ALTER TABLE documents
    ADD COLUMN retention_class text,
    ADD COLUMN retain_until    text,
    ADD COLUMN deleted_at      text;

CREATE TABLE document_versions (
    document_id text NOT NULL REFERENCES documents(id),
    version     int NOT NULL,
    locator     text NOT NULL,          -- blob:<keyed content hash>; the plaintext hash is sha256
    sha256      text NOT NULL,
    size        bigint NOT NULL,
    created_at  text NOT NULL,
    created_by  text NOT NULL,
    reason      text NOT NULL,
    PRIMARY KEY (document_id, version)
);

CREATE TABLE legal_holds (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id      text NOT NULL REFERENCES clients(id),
    document_id    text REFERENCES documents(id),
    reason         text NOT NULL,
    placed_by      text NOT NULL,
    placed_at      text NOT NULL,
    released_by    text,
    released_at    text,
    release_reason text
);

CREATE TABLE deletion_receipts (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id     text NOT NULL,
    client_id       text,
    sha256          text NOT NULL,
    locators        text NOT NULL,
    retention_class text,
    retain_until    text,
    deleted_by      text NOT NULL,
    deleted_at      text NOT NULL,
    reason          text NOT NULL
);

CREATE INDEX document_versions_locator ON document_versions (locator);
CREATE INDEX legal_holds_client ON legal_holds (client_id) WHERE released_at IS NULL;

CREATE TRIGGER document_versions_immutable BEFORE UPDATE OR DELETE ON document_versions FOR EACH ROW EXECUTE FUNCTION forbid_change();
CREATE TRIGGER deletion_receipts_immutable BEFORE UPDATE OR DELETE ON deletion_receipts FOR EACH ROW EXECUTE FUNCTION forbid_change();
CREATE TRIGGER document_versions_no_truncate BEFORE TRUNCATE ON document_versions FOR EACH STATEMENT EXECUTE FUNCTION forbid_change();
CREATE TRIGGER deletion_receipts_no_truncate BEFORE TRUNCATE ON deletion_receipts FOR EACH STATEMENT EXECUTE FUNCTION forbid_change();

-- A hold is released, never deleted; only its release columns change.
CREATE FUNCTION legal_hold_release_only() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'legal holds are released, never deleted' USING ERRCODE = 'AL006';
    END IF;
    IF OLD.released_at IS NOT NULL OR (NEW.client_id, NEW.document_id, NEW.reason, NEW.placed_by, NEW.placed_at)
           IS DISTINCT FROM (OLD.client_id, OLD.document_id, OLD.reason, OLD.placed_by, OLD.placed_at) THEN
        RAISE EXCEPTION 'a legal hold can only be released, once' USING ERRCODE = 'AL006';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER legal_holds_release_only BEFORE UPDATE OR DELETE ON legal_holds FOR EACH ROW EXECUTE FUNCTION legal_hold_release_only();

ALTER TABLE document_versions ENABLE ROW LEVEL SECURITY;
CREATE POLICY scope_document_versions ON document_versions
    USING (EXISTS (SELECT 1 FROM documents d WHERE d.id = document_versions.document_id))
    WITH CHECK (EXISTS (SELECT 1 FROM documents d WHERE d.id = document_versions.document_id));
ALTER TABLE legal_holds ENABLE ROW LEVEL SECURITY;
CREATE POLICY scope_legal_holds ON legal_holds USING (visible(client_id)) WITH CHECK (visible(client_id));
ALTER TABLE deletion_receipts ENABLE ROW LEVEL SECURITY;
CREATE POLICY scope_deletion_receipts ON deletion_receipts USING (visible(client_id)) WITH CHECK (visible(client_id));

GRANT SELECT, INSERT ON document_versions, deletion_receipts TO {{app_role}};
GRANT SELECT, INSERT ON legal_holds TO {{app_role}};
GRANT UPDATE (released_by, released_at, release_reason) ON legal_holds TO {{app_role}};
