-- Facts never overwrite (backlog F-07): an append-only assertion log per return, and conflicts that a person resolves.
-- Same columns and formats as the SQLite schema in agentledger.returns.store. Values are sealed with the firm key.

CREATE TABLE fact_assertions (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_id   text NOT NULL REFERENCES tax_returns(id),
    path        text NOT NULL,
    value       text NOT NULL,
    source      text NOT NULL,
    source_ref  text,
    asserted_by text NOT NULL,
    asserted_at text NOT NULL,
    supersedes  bigint REFERENCES fact_assertions(id)
);
CREATE INDEX fact_assertions_path ON fact_assertions (return_id, path, id);

CREATE TABLE fact_conflicts (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_id      text NOT NULL REFERENCES tax_returns(id),
    path           text NOT NULL,
    anchor         text NOT NULL,
    document_id    text NOT NULL,
    box            text,
    current_value  text NOT NULL,
    proposed_value text NOT NULL,
    current_source text NOT NULL,
    raised_by      text NOT NULL,
    raised_at      text NOT NULL,
    resolution     text CHECK (resolution IN ('kept', 'replaced')),
    resolved_by    text,
    resolved_at    text,
    note           text
);
CREATE INDEX fact_conflicts_open ON fact_conflicts (return_id) WHERE resolved_at IS NULL;

CREATE TRIGGER fact_assertions_immutable BEFORE UPDATE OR DELETE ON fact_assertions FOR EACH ROW EXECUTE FUNCTION forbid_change();
CREATE TRIGGER fact_assertions_no_truncate BEFORE TRUNCATE ON fact_assertions FOR EACH STATEMENT EXECUTE FUNCTION forbid_change();

-- A conflict is resolved once; nothing else about it changes, and it is never deleted.
CREATE FUNCTION fact_conflict_resolve_once() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' OR OLD.resolved_at IS NOT NULL
       OR (NEW.return_id, NEW.path, NEW.anchor, NEW.document_id, NEW.current_value, NEW.proposed_value, NEW.raised_at)
          IS DISTINCT FROM (OLD.return_id, OLD.path, OLD.anchor, OLD.document_id, OLD.current_value, OLD.proposed_value, OLD.raised_at) THEN
        RAISE EXCEPTION 'a fact conflict is resolved once (append-only)' USING ERRCODE = 'AL006';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER fact_conflicts_resolve_once BEFORE UPDATE OR DELETE ON fact_conflicts FOR EACH ROW EXECUTE FUNCTION fact_conflict_resolve_once();

ALTER TABLE fact_assertions ENABLE ROW LEVEL SECURITY;
CREATE POLICY scope_fact_assertions ON fact_assertions
    USING (EXISTS (SELECT 1 FROM tax_returns t WHERE t.id = fact_assertions.return_id))
    WITH CHECK (EXISTS (SELECT 1 FROM tax_returns t WHERE t.id = fact_assertions.return_id));
ALTER TABLE fact_conflicts ENABLE ROW LEVEL SECURITY;
CREATE POLICY scope_fact_conflicts ON fact_conflicts
    USING (EXISTS (SELECT 1 FROM tax_returns t WHERE t.id = fact_conflicts.return_id))
    WITH CHECK (EXISTS (SELECT 1 FROM tax_returns t WHERE t.id = fact_conflicts.return_id));

GRANT SELECT, INSERT ON fact_assertions, fact_conflicts TO {{app_role}};
GRANT UPDATE (resolution, resolved_by, resolved_at, note) ON fact_conflicts TO {{app_role}};
