-- Re-audit of 952ee96: write-ahead evidence deletion, statutory retention inputs, superseded fact conflicts and the
-- dispositions of filed documents a return does not use. Same columns and rules as the SQLite schemas.

-- Retention needs a person's confirmation of the tax year and class (finding 5).
ALTER TABLE documents
    ADD COLUMN retention_confirmed_by text,
    ADD COLUMN retention_confirmed_at text;

-- What retention is counted from: filings, amendments, payments, "no return required" (finding 5).
CREATE TABLE tax_year_events (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id   text NOT NULL REFERENCES clients(id),
    tax_year    int NOT NULL,
    kind        text NOT NULL CHECK (kind IN ('filed', 'amended', 'payment', 'not_required', 'owners_filed')),
    occurred_on text NOT NULL,
    form        text NOT NULL,
    period      text CHECK (period IS NULL OR period IN ('Q1', 'Q2', 'Q3', 'Q4')),
    due_on      text,
    note        text NOT NULL,
    recorded_by text NOT NULL,
    recorded_at text NOT NULL
);
CREATE INDEX tax_year_events_year ON tax_year_events (client_id, tax_year);

-- A filed document moved to another client: holds on the client it left still cover it.
CREATE TABLE document_moves (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id text NOT NULL REFERENCES documents(id),
    from_client text NOT NULL,
    to_client   text NOT NULL,
    reason      text NOT NULL,
    moved_by    text NOT NULL,
    moved_at    text NOT NULL
);
CREATE INDEX document_moves_document ON document_moves (document_id);

-- A basis record whose property was disposed of, released by a CPA (finding 5).
CREATE TABLE basis_releases (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id       text NOT NULL REFERENCES documents(id),
    disposed_tax_year int NOT NULL,
    note              text NOT NULL,
    released_by       text NOT NULL,
    released_at       text NOT NULL
);

-- Write-ahead deletion (finding 4): pending object deletions committed with the receipt, and every outcome.
CREATE TABLE blob_deletions (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_id  bigint NOT NULL REFERENCES deletion_receipts(id),
    document_id text NOT NULL,
    locator     text NOT NULL,
    created_at  text NOT NULL
);
CREATE TABLE blob_deletion_results (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deletion_id bigint NOT NULL REFERENCES blob_deletions(id),
    outcome     text NOT NULL CHECK (outcome IN ('started', 'deleted', 'failed', 'kept_shared')),
    detail      text NOT NULL DEFAULT '',
    at          text NOT NULL
);
CREATE INDEX blob_deletion_results_deletion ON blob_deletion_results (deletion_id);

-- A conflict whose proposal changed or disappeared is closed as superseded (finding 2).
ALTER TABLE fact_conflicts DROP CONSTRAINT fact_conflicts_resolution_check;
ALTER TABLE fact_conflicts ADD CONSTRAINT fact_conflicts_resolution_check
    CHECK (resolution IN ('kept', 'replaced', 'superseded'));
-- One open conflict per field, decided by the database when two populations overlap. A 952ee96 store could hold two
-- on one field: the older ones are retired as superseded first.
UPDATE fact_conflicts SET resolution = 'superseded', resolved_by = 'upgrade', resolved_at = to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"+00:00"'),
    note = 'one open conflict per field (upgrade): a newer conflict on this field is open'
    WHERE resolved_at IS NULL AND id NOT IN (SELECT max(id) FROM fact_conflicts WHERE resolved_at IS NULL GROUP BY return_id, anchor);
CREATE UNIQUE INDEX fact_conflicts_one_open ON fact_conflicts (return_id, anchor) WHERE resolved_at IS NULL;

-- Every document a version of a return relied on, in clear: retention counts the return's year (finding 5).
CREATE TABLE return_document_uses (
    return_id     text NOT NULL REFERENCES tax_returns(id),
    document_id   text NOT NULL,
    first_version int NOT NULL,
    at            text NOT NULL,
    PRIMARY KEY (return_id, document_id)
);
CREATE INDEX return_document_uses_document ON return_document_uses (document_id);

-- What retention needs to know about a return version, in clear: a carryover used, foreign tax shown (finding 5).
CREATE TABLE return_retention_facts (
    return_id text NOT NULL REFERENCES tax_returns(id),
    version   int NOT NULL,
    kind      text NOT NULL CHECK (kind IN ('carryover', 'foreign_tax')),
    detail    text NOT NULL,
    at        text NOT NULL,
    PRIMARY KEY (return_id, version, kind)
);

-- Filed documents a return does not use, accounted for by a person (finding 1, path f).
CREATE TABLE return_document_dispositions (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_id   text NOT NULL REFERENCES tax_returns(id),
    document_id text NOT NULL,
    disposition text NOT NULL CHECK (disposition IN ('entered_by_hand', 'not_applicable')),
    note        text NOT NULL,
    actor       text NOT NULL,
    at          text NOT NULL
);

DO $$
DECLARE
    t text;
BEGIN
    FOREACH t IN ARRAY ARRAY['tax_year_events', 'blob_deletions', 'blob_deletion_results', 'return_document_dispositions',
                             'return_document_uses', 'document_moves', 'return_retention_facts', 'basis_releases'] LOOP
        EXECUTE format('CREATE TRIGGER %I BEFORE UPDATE OR DELETE ON %I FOR EACH ROW EXECUTE FUNCTION forbid_change()',
                       t || '_immutable', t);
        EXECUTE format('CREATE TRIGGER %I BEFORE TRUNCATE ON %I FOR EACH STATEMENT EXECUTE FUNCTION forbid_change()',
                       t || '_no_truncate', t);
    END LOOP;
END $$;

ALTER TABLE tax_year_events ENABLE ROW LEVEL SECURITY;
CREATE POLICY scope_tax_year_events ON tax_year_events USING (visible(client_id)) WITH CHECK (visible(client_id));
ALTER TABLE blob_deletions ENABLE ROW LEVEL SECURITY;
CREATE POLICY scope_blob_deletions ON blob_deletions
    USING (EXISTS (SELECT 1 FROM deletion_receipts r WHERE r.id = blob_deletions.receipt_id))
    WITH CHECK (EXISTS (SELECT 1 FROM deletion_receipts r WHERE r.id = blob_deletions.receipt_id));
ALTER TABLE blob_deletion_results ENABLE ROW LEVEL SECURITY;
CREATE POLICY scope_blob_deletion_results ON blob_deletion_results
    USING (EXISTS (SELECT 1 FROM blob_deletions b WHERE b.id = blob_deletion_results.deletion_id))
    WITH CHECK (EXISTS (SELECT 1 FROM blob_deletions b WHERE b.id = blob_deletion_results.deletion_id));
ALTER TABLE return_document_dispositions ENABLE ROW LEVEL SECURITY;
CREATE POLICY scope_return_document_dispositions ON return_document_dispositions
    USING (EXISTS (SELECT 1 FROM tax_returns t WHERE t.id = return_document_dispositions.return_id))
    WITH CHECK (EXISTS (SELECT 1 FROM tax_returns t WHERE t.id = return_document_dispositions.return_id));

ALTER TABLE document_moves ENABLE ROW LEVEL SECURITY;
CREATE POLICY scope_document_moves ON document_moves USING (visible(from_client) OR visible(to_client))
    WITH CHECK (visible(from_client) AND visible(to_client));
ALTER TABLE basis_releases ENABLE ROW LEVEL SECURITY;
CREATE POLICY scope_basis_releases ON basis_releases
    USING (EXISTS (SELECT 1 FROM documents d WHERE d.id = basis_releases.document_id))
    WITH CHECK (EXISTS (SELECT 1 FROM documents d WHERE d.id = basis_releases.document_id));
ALTER TABLE return_retention_facts ENABLE ROW LEVEL SECURITY;
CREATE POLICY scope_return_retention_facts ON return_retention_facts
    USING (EXISTS (SELECT 1 FROM tax_returns t WHERE t.id = return_retention_facts.return_id))
    WITH CHECK (EXISTS (SELECT 1 FROM tax_returns t WHERE t.id = return_retention_facts.return_id));
ALTER TABLE return_document_uses ENABLE ROW LEVEL SECURITY;
CREATE POLICY scope_return_document_uses ON return_document_uses
    USING (EXISTS (SELECT 1 FROM tax_returns t WHERE t.id = return_document_uses.return_id))
    WITH CHECK (EXISTS (SELECT 1 FROM tax_returns t WHERE t.id = return_document_uses.return_id));

GRANT SELECT, INSERT ON tax_year_events, blob_deletions, blob_deletion_results, return_document_dispositions,
    return_document_uses, document_moves, return_retention_facts, basis_releases TO {{app_role}};
